# Generated by Django 4.1.6 on 2023-02-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_options_alter_category_cat_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='identificador')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='descripción')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('images', models.ImageField(upload_to='photos/products', verbose_name='fotos')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponibilidad')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_date', models.DateTimeField(verbose_name='fecha de modificación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
