# Generated by Django 4.1.6 on 2023-02-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_product_name_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
