# Generated by Django 4.1.6 on 2023-02-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_images_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100, verbose_name='tipo')),
                ('variation_value', models.CharField(max_length=100, verbose_name='valor')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='fecha de creación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='producto')),
            ],
        ),
    ]
