# Generated by Django 4.1.6 on 2023-02-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_is_available_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Talla')], max_length=100, verbose_name='tipo'),
        ),
    ]
