# Generated by Django 4.1.6 on 2023-02-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_variation_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='variation_value',
            new_name='value',
        ),
    ]
